stages:
  split:
    cmd: python src/data/split_dataset.py
    deps:
    - data/raw_data
    - src/data/split_dataset.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
  
  normalize:
    cmd: python src/data/normalisation_dataset.py
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - src/data/normalisation_dataset.py
    outs:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test_scaled.csv

  gridSearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_parameters.pkl

  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_parameters.pkl
    - src/models/train_model.py
    outs:
    - models/best_model.pkl
  
  metrics:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/best_model.pkl
    - src/models/evaluate_model.py
    metrics:
    - metrics/metrics.json